device: cuda

data:
    data_dir: /mnt/ceph_rbd/imagenet-1k/data
    global_batch_size: 1024
    local_batch_size: 128 # change to 0 to use global_batch_size
    train_subset: 2048 # 0 will use the full dataset
    val_subset: 512
    gradient_accumulation_freq: -1  # -1 will automatically determine the best frequency for a 128 core cpu
    drop_last_batch: True
    shuffle: True
    n_epochs: 4
    prefetch: 4

opt:
    name: SGD
    momentum: 0.9
    weight_decay: 0.0001

lr_schedule:
    base_lr: 0.002
    end_lr: 0.0001
    decay_steps: 5
    poly_power: 2 

training:
    target_accuracy: 0.759
    benchmark: True
